spring.application.name=CineScore

# Banco de dados em memória (H2) — sem necessidade de banco externo
spring.datasource.url=jdbc:h2:mem:cinescoredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# No Render, a porta vem da variável de ambiente PORT
server.port=${PORT:8080}